### ISSUE TITLE
E1E2: As a Seeker, I can post a new request in a marketplace, describing what I am asking for and how much DAI I am offering, so providers can see what my need is.

### ISSUE THREAD

**Issue by scmatt** [swarmcity/boardwalk-ts#1]
## Abstract:
In Swarm City, interactions happen in marketplaces. A marketplace gives context to a token transfer. 

Users (Seekers) can post new requests in a marketplace, inviting other users (Providers) to reply to their requests.

## How it could work:

In a marketplace, a Seeker fills in a request description and a token amount they are willing to pay for the good or service.

-------

## What it looks like:

<img width="700" alt="Screen Shot 2022-05-04 at 5 14 46 PM" src="https://user-images.githubusercontent.com/103889634/166827055-2d4e0bb2-87b6-4f60-8fd3-801860789e9d.png">

---
On **marketplace**, we see:
- a list of marketplaceItems which may include marketplaceMyItems. Please see [E1E3](https://github.com/swarmcity/boardwalk-ts/issues/2) for more details on this user screen.

On **MY-request,** we see:
- an inputfield for the description, labeled "What are you looking for?"
- an inputfield for the amount, labeled "What would you like to offer?", followed by copy "DAI"
- small copy: "+" and marketplacefee/2 and "DAI fee"
- horizontal divider line
- If, and only if all inputs are valid (**MY-request-input-valid**): copy "Total cost:" and total cost of deal (=amount+marketplacefee/2) and "DAI"
- a big blue icon button with a next icon (disabled until both inputs are valid)
- a blue "i" that when tapped opens the marketplace's description (marketplace description development occurs in S01E05)

The input field "amount" is valid when:
- the amount is a Numeric value that may contain a decimal.
- the total cost (=amount + marketplacefee/2) is less than the user's total balance

The description input is valid when:
- it has at least 1 character

When the big blue button is enabled, and is tapped by the user, the view changes to **MY-request-confirm**.

<img width="700" alt="Screen Shot 2022-05-04 at 5 30 31 PM" src="https://user-images.githubusercontent.com/103889634/166829102-0ab9a9c0-8edd-488f-9337-4a16879ac627.png">

**MY-request-confirm** contains:

- copy: "You're about to post this request for" and (amount+marketplacefee) and "DAI"
- copy: "This can not be undone." and (marketplacefee/2) and "DAI fee is included"
- black x-mark (cancel-button)
- big white button with blue V-mark (confirm-button)
When the user taps the black X-mark (cancel-button), the confirmation process is aborted and the view changes to **MY-request-input-valid** with the inputs still filled in.

When the user taps the big white button with blue V-mark, he triggers the **MY-request-confirm-password** for signing the transaction.

When the white button of **MY-request-confirm-password** is enabled (= when the password input has at least 1 character) and tapped by the user, the page changes to **MY-request-progress**.

**MY-request-progress** is a processing page, in this case the copy on success is "Request is being processed."

Once the transaction is processed, the view changes to page **marketplace** (of that specific marketplace) with the new item visible.

---
## Desktop View
<img width="700" alt="Screenshot 2022-05-12 at 12 25 04" src="https://user-images.githubusercontent.com/9036081/168050193-0f4b40c7-fa0d-4d2d-a337-aff7d327567f.png">

<img width="700" alt="Screen Shot 2022-05-04 at 5 36 29 PM" src="https://user-images.githubusercontent.com/103889634/166829846-64742441-0714-4a6c-ba40-acf801d79b00.png">

<img width="700" alt="Screen Shot 2022-05-04 at 5 36 39 PM" src="https://user-images.githubusercontent.com/103889634/166829892-edf70ba9-9d97-4815-8bbb-f13d87f92df1.png">

**Comment by kikipluche** [comment]
hey @scmatt , i changed the first screenshot of the desktop view, because it was the older version (small detail on the marketplace view), the size does not match your screenshots though...
