### ISSUE TITLE
File input does not work on Chrome

### ISSUE THREAD

**Issue by vojtechsimetka** [swarmcity/boardwalk-ts#104]
![Screenshot 2022-10-14 at 15 55 26](https://user-images.githubusercontent.com/7974813/195864483-fa2c66f5-99aa-4eba-948f-4bc8a854ec47.png)

**Comment by kikipluche** [comment]
same goes for brave

**Comment by vojtechsimetka** [comment]
Yeah both are based on Chrome. Looking into it now but I have no idea why it does not work TBH.

**Comment by vojtechsimetka** [comment]
Looks like this is known issue in chromium browsers and can be resolved by restarting the browser.
