### ISSUE TITLE
show avatar on password unlock

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/boardwalk-ts#105]
if i have an avatar other than default, show my avatar
<img width="449" alt="Screenshot 2022-10-15 at 00 12 39" src="https://user-images.githubusercontent.com/9036081/195951550-e5545352-c6e1-4614-a12c-a14a8d0d7e74.png">

**Comment by vojtechsimetka** [comment]
Fixed in https://github.com/swarmcity/boardwalk-ts/pull/141
