### ISSUE TITLE
hashtagfee is not displayed correctly in confirm post page

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/boardwalk-ts#128]
the hashtagfee on the post new item does not match the text about the hashtagfee on the confirm page
<img width="427" alt="Screenshot 2022-10-17 at 14 25 45" src="https://user-images.githubusercontent.com/9036081/196176713-26168c7a-0f80-4509-bec2-9da7a318c7df.png">
<img width="404" alt="Screenshot 2022-10-17 at 14 25 37" src="https://user-images.githubusercontent.com/9036081/196176723-953307ae-ea47-45b9-a634-a974e518e153.png">

it adds 2.5 fakeDAI as described in the post item, but on confirm it talks about 0.5 fakeDAI

in every marketplace, this occurs

**Comment by vojtechsimetka** [comment]
Fixed in #142
