### ISSUE TITLE
padding on progressing page

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/boardwalk-ts#129]
figma: 
<img width="224" alt="Screenshot 2022-10-17 at 14 30 56" src="https://user-images.githubusercontent.com/9036081/196177602-e45f8dad-2f13-43a6-aa0e-1e0ce67467cc.png">
app: text is too close to the top
<img width="423" alt="Screenshot 2022-10-17 at 14 30 37" src="https://user-images.githubusercontent.com/9036081/196177671-0b6f26d6-34c7-4bb9-8793-564e9612fe07.png">

**Comment by vojtechsimetka** [comment]
closed in #159
