### ISSUE TITLE
show replier (potential provider) rep and make that username clickable

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/boardwalk-ts#154]
in request with replies:
- [x]  set provider rep for the provider (replier)
- [x] make replier username (provider) clickable to go to user's rep page

**Comment by filoozom** [comment]
First part fixed in 3634fd9c5b393649064666b0e6fe8f563413c619

**Comment by filoozom** [comment]
Second part fixed in 2f0679b4339e948d770197c257b160f3454f59c5
