### ISSUE TITLE
box over back button

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/boardwalk-ts#156]
there is a white box that chops off the round button
![Uploading Screenshot 2022-10-20 at 12.06.56.png…]()

**Comment by michelleplur** [comment]
<img width="340" alt="Screenshot 2022-10-21 at 00 42 55" src="https://user-images.githubusercontent.com/52613476/197072886-55de3d8c-f265-4642-9cd7-3934b18429ae.png">
