### ISSUE TITLE
Fix which items show in my item list

### ISSUE THREAD

**Issue by vojtechsimetka** [swarmcity/boardwalk-ts#178]
It should include:

- [x] Items where I am `provider` or `seeker` and are not `done`, `canceled` or `resolved` (fixed in #180)
- [ ] Items where I am `marketplaceOwner` and are `disputed`

Currently it shows in my list items that are in all states and where the user is seeker.

**Comment by matthewcarano** [comment]
Made the second isuue (Items where I am marketplaceOwner and are disputed) into it's own issue:
https://github.com/swarmcity/boardwalk-ts/issues/186

Closing this one out.
