### ISSUE TITLE
More efficient way to get deal creation date and time

### ISSUE THREAD

**Issue by filoozom** [swarmcity/boardwalk-ts#25]
Events don't include the timestamp at which they were emitted, meaning that currently we're fetching one block for every event (so one block per deal). This is not scalable. Caching seems problematic as well.

An alternative could be to emit the timestamp in the [`NewItem` event](https://github.com/swarmcity/boardwalk-contracts/blob/cde1ccb9ec73997f6032cda325876cbdd1fbe495/src/Marketplace.sol#L72-L79).

**Comment by michelleplur** [comment]
can this be closed?
