### ISSUE TITLE
Define a protocol to store profiles

### ISSUE THREAD

**Issue by filoozom** [swarmcity/boardwalk-ts#26]
Currently we're not storing the profile (name, avatar and address) anywhere. Some ideas:
- We could store that in Waku Store and refresh the data periodically
- We could store it on IPFS, but that means additional infrastructure and overhead
- We could store it on Swarm, but it's not ready yet for user generated content because of the non-portability of postage stamps and also involves additional infrastructure
- We could store it in every the deal metadata, but that seems like a waste because of duplication

**Comment by filoozom** [comment]
@michelleplur Apparently option 4 was chosen before for privacy reasons. Could you give more details to that regard?

**Comment by michelleplur** [comment]
I don't think it was chosen for privacy reasons, but for accuracy.
