### ISSUE TITLE
Add a way to cancel items whose metadata was lost

### ISSUE THREAD

**Issue by filoozom** [swarmcity/boardwalk-ts#62]
Right now, we store data in Waku, which can be lost or deleted for various reasons. This is a feature, as we don't want to keep useless data around forever. The data can be refreshed in case it's still necessary. This means that as long as users log back in regularly, they will not lose anything.

However, this causes an issue whereby users might not see their items / deals anymore, but also cannot cancel them from the app. Indeed, we do not display any deals when their metadata is missing, because we cannot know what it is about, so it makes no sense to display it.

Thus, we need a page that allows users to cancel their ongoing deals and get their funds back. It would not display very much as the metadata is missing, but maybe something as simple as "you have x ongoing deals without metadata, click here to reclaim y DAI".

**Comment by kikipluche** [comment]
I suggest we write this down in the documentation we give to Status, so they know that this is a feature that is needed in future.

**Comment by matthewcarano** [comment]
Broke this up into 3 issues: #187 #188 #189, closing this issue.
