### ISSUE TITLE
Update CI to use nodejs v18

### ISSUE THREAD

**Issue by vojtechsimetka** [swarmcity/boardwalk-ts#76]

**Comment by filoozom** [comment]
Do you have more details regarding this? What are the errors?

It seems like `npm run build` works as does `npm run dev` and some pages I navigated to, although I didn't do a full test.

**Comment by vojtechsimetka** [comment]
Oh my bad you are right. It just failed to install for me in the past on node v18 and wen it happened now I assumed it still does not work. It does work.

That being said, I would suggest we update the CI actions to use node v18. WDYT?

**Comment by filoozom** [comment]
> I would suggest we update the CI actions to use node v18. WDYT?

Sure, that seems like a good idea. Want me to do it?

**Comment by vojtechsimetka** [comment]
Yes please
